## **Chapter 3 exercises**

###EX 1

In [14]:
a = list(range(9))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
a = torch.tensor(a)
a

<ipython-input-17-115972a5e503>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(a)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

.view() reshapes the original tensor

In [19]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [24]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [31]:
c.storage_offset()

4

Note: The offset has to do with the storage of the tensor. When I define a new tensor from scratch, the offset is 0. When I start creating new tensors by slicing (or other operations) on my original tensor then the offset changes (along with the stride of course). However, the location where these new tensors are saved is the same.

## EX 2

I will choose cosine.

In [37]:
cosa = torch.cos(a)
cosa

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])